<?php

namespace Hydrators;

use Doctrine\ODM\MongoDB\DocumentManager;
use Doctrine\ODM\MongoDB\Hydrator\HydratorException;
use Doctrine\ODM\MongoDB\Hydrator\HydratorInterface;
use Doctrine\ODM\MongoDB\Query\Query;
use Doctrine\ODM\MongoDB\UnitOfWork;
use Doctrine\ODM\MongoDB\Mapping\ClassMetadata;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ODM. DO NOT EDIT THIS FILE.
 */
class AppDocumentRomaneioHydrator implements HydratorInterface
{
    private $dm;
    private $unitOfWork;
    private $class;

    public function __construct(DocumentManager $dm, UnitOfWork $uow, ClassMetadata $class)
    {
        $this->dm = $dm;
        $this->unitOfWork = $uow;
        $this->class = $class;
    }

    public function hydrate(object $document, array $data, array $hints = array()): array
    {
        $hydratedData = array();

        /** @Field(type="id") */
        if (isset($data['_id']) || (! empty($this->class->fieldMappings['id']['nullable']) && array_key_exists('_id', $data))) {
            $value = $data['_id'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['id']['type'];
                $return = $value instanceof \MongoDB\BSON\ObjectId ? (string) $value : $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['id']->setValue($document, $return);
            $hydratedData['id'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['driverName']) || (! empty($this->class->fieldMappings['driverName']['nullable']) && array_key_exists('driverName', $data))) {
            $value = $data['driverName'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['driverName']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['driverName']->setValue($document, $return);
            $hydratedData['driverName'] = $return;
        }

        /** @Field(type="string") */
        if (isset($data['type']) || (! empty($this->class->fieldMappings['type']['nullable']) && array_key_exists('type', $data))) {
            $value = $data['type'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['type']['type'];
                $return = (string) $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['type']->setValue($document, $return);
            $hydratedData['type'] = $return;
        }

        /** @Field(type="collection") */
        if (isset($data['items']) || (! empty($this->class->fieldMappings['items']['nullable']) && array_key_exists('items', $data))) {
            $value = $data['items'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['items']['type'];
                $return = $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['items']->setValue($document, $return);
            $hydratedData['items'] = $return;
        }

        /** @Field(type="timestamp") */
        if (isset($data['createDate']) || (! empty($this->class->fieldMappings['createDate']['nullable']) && array_key_exists('createDate', $data))) {
            $value = $data['createDate'];
            if ($value !== null) {
                $typeIdentifier = $this->class->fieldMappings['createDate']['type'];
                $return = $value;
            } else {
                $return = null;
            }
            $this->class->reflFields['createDate']->setValue($document, $return);
            $hydratedData['createDate'] = $return;
        }
        return $hydratedData;
    }
}