twig:
    paths: ['%kernel.project_dir%/templates']
    form_themes: ['bootstrap_4_layout.html.twig']
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    cache: false
    globals:
        version: '%interface_version%'