<?php

namespace ContainerJD9H5cQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NblINS4Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.NblINS4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NblINS4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'dateFunctions' => ['privates', 'App\\Utils\\Andresmei\\DateFunctions', 'getDateFunctionsService', true],
            'repository' => ['privates', 'App\\Repository\\ManualOrderReportRepository', 'getManualOrderReportRepositoryService', true],
        ], [
            'dateFunctions' => 'App\\Utils\\Andresmei\\DateFunctions',
            'repository' => 'App\\Repository\\ManualOrderReportRepository',
        ]);
    }
}
