<?php

namespace ContainerJD9H5cQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_J42OHEGService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.j42OHEG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.j42OHEG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'setter' => ['privates', 'App\\Utils\\Generic\\Crud', 'getCrudService', true],
        ], [
            'setter' => 'App\\Utils\\Generic\\Crud',
        ]);
    }
}
