<?php

namespace ContainerJD9H5cQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6ceFqBYService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.6ceFqBY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6ceFqBY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'surveyModel' => ['privates', 'App\\Model\\SurveyModel', 'getSurveyModelService', true],
        ], [
            'surveyModel' => 'App\\Model\\SurveyModel',
        ]);
    }
}
