<?php

namespace ContainerJD9H5cQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XI58FCService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.xI58_fC' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.xI58_fC'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'form' => ['privates', 'App\\Utils\\Andresmei\\Form', 'getFormService', true],
        ], [
            'form' => 'App\\Utils\\Andresmei\\Form',
        ]);
    }
}
