<?php

namespace ContainerJD9H5cQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getManualOrderControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\ManualOrderController' shared autowired service.
     *
     * @return \App\Controller\ManualOrderController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'CSRFTokenCheck.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'ManualOrderController.php';

        $container->services['App\\Controller\\ManualOrderController'] = $instance = new \App\Controller\ManualOrderController(($container->privates['App\\Repository\\ManualOrderReportRepository'] ?? $container->load('getManualOrderReportRepositoryService')));

        $instance->setContainer(($container->privates['.service_locator.5nX7ca3'] ?? $container->get_ServiceLocator_5nX7ca3Service())->withContext('App\\Controller\\ManualOrderController', $container));

        return $instance;
    }
}
