<?php

namespace ContainerJD9H5cQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getOrderPredictionModelService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Model\OrderPredictionModel' shared autowired service.
     *
     * @return \App\Model\OrderPredictionModel
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Model'.\DIRECTORY_SEPARATOR.'OrderPredictionModel.php';

        return $container->privates['App\\Model\\OrderPredictionModel'] = new \App\Model\OrderPredictionModel(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->privates['App\\Repository\\OrderPredictionRepository'] ?? $container->load('getOrderPredictionRepositoryService')));
    }
}
