<?php

namespace ContainerJD9H5cQ;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPredictionControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\PredictionController' shared autowired service.
     *
     * @return \App\Controller\PredictionController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'PredictionController.php';

        $container->services['App\\Controller\\PredictionController'] = $instance = new \App\Controller\PredictionController();

        $instance->setContainer(($container->privates['.service_locator.5nX7ca3'] ?? $container->get_ServiceLocator_5nX7ca3Service())->withContext('App\\Controller\\PredictionController', $container));

        return $instance;
    }
}
