<?php

namespace ContainerZs75vn5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Uh7zYdBService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.uh7zYdB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uh7zYdB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'model' => ['privates', 'App\\Model\\ProductionCountModel', 'getProductionCountModelService', true],
            'nameModel' => ['privates', 'App\\Model\\ModelsModel', 'getModelsModelService', true],
            'productionCountRepository' => ['privates', 'App\\Repository\\ProductionCountRepository', 'getProductionCountRepositoryService', true],
        ], [
            'model' => 'App\\Model\\ProductionCountModel',
            'nameModel' => 'App\\Model\\ModelsModel',
            'productionCountRepository' => 'App\\Repository\\ProductionCountRepository',
        ]);
    }
}
