<?php

namespace ContainerZs75vn5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6B5TqXNService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.6B5TqXN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.6B5TqXN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'listModel' => ['privates', 'App\\Model\\ListModel', 'getListModelService', true],
        ], [
            'listModel' => 'App\\Model\\ListModel',
        ]);
    }
}
