<?php

namespace ContainerZs75vn5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JhkaX4zService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.jhkaX4z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.jhkaX4z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'manualOrderReportRepository' => ['privates', 'App\\Repository\\ManualOrderReportRepository', 'getManualOrderReportRepositoryService', true],
        ], [
            'manualOrderReportRepository' => 'App\\Repository\\ManualOrderReportRepository',
        ]);
    }
}
