<?php

namespace ContainerZs75vn5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Y5Jcv4YService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.y5Jcv4Y' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.y5Jcv4Y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'crud' => ['privates', 'App\\Utils\\Generic\\Crud', 'getCrudService', true],
        ], [
            'crud' => 'App\\Utils\\Generic\\Crud',
        ]);
    }
}
