<?php

namespace ContainerZs75vn5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SvT6Ko0Service extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.svT6Ko0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.svT6Ko0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'dcm' => ['services', 'doctrine_mongodb.odm.default_document_manager', 'getDoctrineMongodb_Odm_DefaultDocumentManagerService', true],
            'model' => ['privates', 'App\\Model\\FormModel', 'getFormModelService', true],
        ], [
            'dcm' => '?',
            'model' => 'App\\Model\\FormModel',
        ]);
    }
}
