<?php

namespace ContainerZs75vn5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_XE54fCbService extends App_KernelProdContainer
{
    /*
     * Gets the private '.service_locator.XE54fCb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.XE54fCb'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'encoder' => ['services', 'security.password_encoder', 'getSecurity_PasswordEncoderService', true],
            'model' => ['privates', 'App\\Model\\UserModel', 'getUserModelService', true],
        ], [
            'encoder' => '?',
            'model' => 'App\\Model\\UserModel',
        ]);
    }
}
