<?php

namespace ContainerZs75vn5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDateFunctionsService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Utils\Andresmei\DateFunctions' shared autowired service.
     *
     * @return \App\Utils\Andresmei\DateFunctions
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Utils'.\DIRECTORY_SEPARATOR.'Andresmei'.\DIRECTORY_SEPARATOR.'DateFunctions.php';

        return $container->privates['App\\Utils\\Andresmei\\DateFunctions'] = new \App\Utils\Andresmei\DateFunctions();
    }
}
