<?php

namespace ContainerZs75vn5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getFormService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Utils\Andresmei\Form' shared autowired service.
     *
     * @return \App\Utils\Andresmei\Form
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Utils'.\DIRECTORY_SEPARATOR.'GenericContainer.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Utils'.\DIRECTORY_SEPARATOR.'Andresmei'.\DIRECTORY_SEPARATOR.'Form.php';

        return $container->privates['App\\Utils\\Andresmei\\Form'] = new \App\Utils\Andresmei\Form(($container->services['doctrine.orm.default_entity_manager'] ?? $container->getDoctrine_Orm_DefaultEntityManagerService()), ($container->services['.container.private.twig'] ?? $container->load('get_Container_Private_TwigService')));
    }
}
