<?php

namespace ContainerZs75vn5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTruckControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\TruckController' shared autowired service.
     *
     * @return \App\Controller\TruckController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Controller'.\DIRECTORY_SEPARATOR.'TruckController.php';

        $container->services['App\\Controller\\TruckController'] = $instance = new \App\Controller\TruckController();

        $instance->setContainer(($container->privates['.service_locator.5nX7ca3'] ?? $container->get_ServiceLocator_5nX7ca3Service())->withContext('App\\Controller\\TruckController', $container));

        return $instance;
    }
}
