check:
  allowNegativeStock:
    name:     'allow_negative_stock'
    label:    'Permitir estoque negativo'
    tooltip:  'Permitir reserva de produtos mesmo se não houver estoque'
  allowReserve:
    name:     'allow_reserve'
    label:    'Habilitar função de reservar'
    tooltip:  'Habilita função de reserva no sistema'
  allowSameCpf:
    name:     'allow_same_cpf'
    label:    'Permitir clientes com mesmo cpf'
    tooltip:  'Permiti que clientes diferentes possuam mesmo CPF'
  allowNoCpf:
    name:     'allow_no_cpf'
    label:    'Permitir cadastro sem CPF'
    tooltip:  'Permitir cadastro de clientes sem C.P.F, cuidado com essa opção'
  CheckCNPJ:
    name:     'check_cnpj'
    label:    'Verifica validade de cnpj'
    tooltip:  'Sistema verificará cnpj cadastrado'

images:
  logoImage:
    name:     'logo_image_path'
    label:    'Logo que será posto em formularios'
    alt:      'Logomarca da empresa no sistema'

surveyData:
  AllowSurvey:
    name:     'allow_survey'
    label:    'Habilitar criação de pesquisa de satisfação'
    tooltip:  'Mostrar botão de criação de pesquisas de satisfação'