allow_negative_stock: false
allow_reserve: false
allow_same_cpf: false
allow_no_cpf: true
check_cnpj: true
logo_image_path: sys/logo_img/logo.png
allow_survey: false
survey_question:
    1: { text: 'Qual seu nome, meu amiginho?', type: text, alternatives: {  } }
    2: { text: 'Qual seu grau de escolaridade', type: radio, alternatives: { 1: 'ensino médio', 2: 'ensino superior', 3: 'eu inventei o ensino!!!!!!!!!!!!!!!!!!' } }
