allow_negative_stock: true
allow_reserve: false
allow_same_cpf: true
allow_no_cpf: false
check_cnpj: false
logo_image_path: 'sys/logo_img/logo.png'
survey_question:
  1:
      'text': 'Qual seu nome, meu amiginho?'
      'type': 'text'
      'alternatives': []
  2:
      'text': 'Qual seu grau de escolaridade'
      'type': 'radio'
      'alternatives': ['nenhuma', 'ensino médio', 'ensino superior', 'eu inventei o ensino!!!!!!!!!!!!!!!!!!']
  3:
      'text': 'You know what syncron summon is, you brat!?'
      'type': 'radio'
      'alternatives': ['sim', 'não']
