- namediv: Items

- name: 'Relatórios'
  route: '#'
  icon: 'fa-file-alt'
  collapseName: 'collapse1'
  subitems:
    - name: 'Relatórios'
      items:
        - name: 'Todos os Relatorios'
          route: '/report'
    - name: 'Criar relatórios'
      items:
        - name: 'Produção'
          route: '/report/productionCount'
        - name: 'Caminhão'
          route: '/truck'

- name: 'Pedidos'
  route: '#'
  icon: 'fa-shopping-cart'
  collapseName: 'collapse2'
  subitems:
    - name: 'Paginas'
      items:
        - name: 'Criar pedido'
          route: '/forms/order'
        - name: 'Lista de pedidos'
          route: '/order'

- name: 'Formularios'
  route: '#'
  icon: 'fa-sticky-note'
  collapseName: 'collapse3'
  subitems:
    - name: 'Todos os formulários'
      items: 
        - name: 'Todos os formulários'
          route: '/forms'
    - name: 'Caminhão'
      items:
        - name: 'Devolução'
          route: '/forms/remand'
        - name: 'Carta frete'
          route: '/forms/freight-letter'
        - name: 'Etiqueta'
          route: '/forms/tag'
        - name: 'Recibo'
          route: '/forms/receipt'
        - name: 'Romaneio'
          route: '/forms/romaneio'
          
- divider: true
- namediv: 'Sistema'

- name: 'Registros'
  route: '/register'
  icon: 'fa-address-card'

- name: 'Configuração'
  route: '/register/configuration'
  icon: 'fa-cog'

- divider: true
