<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Boleto extends \App\Entity\Boleto implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Boleto' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Boleto' . "\0" . 'boletoCustomerOwner', '' . "\0" . 'App\\Entity\\Boleto' . "\0" . 'boletoNumber', '' . "\0" . 'App\\Entity\\Boleto' . "\0" . 'boletoStatus', '' . "\0" . 'App\\Entity\\Boleto' . "\0" . 'boletoPaymentDate', '' . "\0" . 'App\\Entity\\Boleto' . "\0" . 'boletoValue', '' . "\0" . 'App\\Entity\\Boleto' . "\0" . 'boletoInstallment', '' . "\0" . 'App\\Entity\\Boleto' . "\0" . 'boletoVencimento', '' . "\0" . 'App\\Entity\\Boleto' . "\0" . 'boletoProvisionamentoDate', '' . "\0" . 'App\\Entity\\Boleto' . "\0" . 'boletoPorContaStatus', 'lastUpdate'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Boleto' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Boleto' . "\0" . 'boletoCustomerOwner', '' . "\0" . 'App\\Entity\\Boleto' . "\0" . 'boletoNumber', '' . "\0" . 'App\\Entity\\Boleto' . "\0" . 'boletoStatus', '' . "\0" . 'App\\Entity\\Boleto' . "\0" . 'boletoPaymentDate', '' . "\0" . 'App\\Entity\\Boleto' . "\0" . 'boletoValue', '' . "\0" . 'App\\Entity\\Boleto' . "\0" . 'boletoInstallment', '' . "\0" . 'App\\Entity\\Boleto' . "\0" . 'boletoVencimento', '' . "\0" . 'App\\Entity\\Boleto' . "\0" . 'boletoProvisionamentoDate', '' . "\0" . 'App\\Entity\\Boleto' . "\0" . 'boletoPorContaStatus', 'lastUpdate'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Boleto $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getBoletoCustomerOwner(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBoletoCustomerOwner', []);

        return parent::getBoletoCustomerOwner();
    }

    /**
     * {@inheritDoc}
     */
    public function setBoletoCustomerOwner(string $boletoCustomerOwner): \App\Entity\Boleto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBoletoCustomerOwner', [$boletoCustomerOwner]);

        return parent::setBoletoCustomerOwner($boletoCustomerOwner);
    }

    /**
     * {@inheritDoc}
     */
    public function getBoletoNumber(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBoletoNumber', []);

        return parent::getBoletoNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setBoletoNumber(string $boletoNumber): \App\Entity\Boleto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBoletoNumber', [$boletoNumber]);

        return parent::setBoletoNumber($boletoNumber);
    }

    /**
     * {@inheritDoc}
     */
    public function getBoletoStatus(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBoletoStatus', []);

        return parent::getBoletoStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function getBoletoStatusExtense(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBoletoStatusExtense', []);

        return parent::getBoletoStatusExtense();
    }

    /**
     * {@inheritDoc}
     */
    public function setBoletoStatus(int $boletoStatus): \App\Entity\Boleto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBoletoStatus', [$boletoStatus]);

        return parent::setBoletoStatus($boletoStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function getBoletoPaymentDate(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBoletoPaymentDate', []);

        return parent::getBoletoPaymentDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setBoletoPaymentDate(?string $boletoPaymentDate): \App\Entity\Boleto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBoletoPaymentDate', [$boletoPaymentDate]);

        return parent::setBoletoPaymentDate($boletoPaymentDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getBoletoValue(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBoletoValue', []);

        return parent::getBoletoValue();
    }

    /**
     * {@inheritDoc}
     */
    public function setBoletoValue(float $boletoValue): \App\Entity\Boleto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBoletoValue', [$boletoValue]);

        return parent::setBoletoValue($boletoValue);
    }

    /**
     * {@inheritDoc}
     */
    public function getBoletoInstallment(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBoletoInstallment', []);

        return parent::getBoletoInstallment();
    }

    /**
     * {@inheritDoc}
     */
    public function setBoletoInstallment(int $boletoInstallment): \App\Entity\Boleto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBoletoInstallment', [$boletoInstallment]);

        return parent::setBoletoInstallment($boletoInstallment);
    }

    /**
     * {@inheritDoc}
     */
    public function getBoletoVencimento(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBoletoVencimento', []);

        return parent::getBoletoVencimento();
    }

    /**
     * {@inheritDoc}
     */
    public function setBoletoVencimento(string $boletoVencimento): \App\Entity\Boleto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBoletoVencimento', [$boletoVencimento]);

        return parent::setBoletoVencimento($boletoVencimento);
    }

    /**
     * {@inheritDoc}
     */
    public function getBoletoProvisionamentoDate(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBoletoProvisionamentoDate', []);

        return parent::getBoletoProvisionamentoDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setBoletoProvisionamentoDate(?\DateTimeInterface $boletoProvisionamentoDate): \App\Entity\Boleto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBoletoProvisionamentoDate', [$boletoProvisionamentoDate]);

        return parent::setBoletoProvisionamentoDate($boletoProvisionamentoDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getBoletoPorContaStatus(): ?array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBoletoPorContaStatus', []);

        return parent::getBoletoPorContaStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setBoletoPorContaStatus(?array $boletoPorContaStatus): \App\Entity\Boleto
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBoletoPorContaStatus', [$boletoPorContaStatus]);

        return parent::setBoletoPorContaStatus($boletoPorContaStatus);
    }

    /**
     * {@inheritDoc}
     */
    public function __toArray(): ?array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toArray', []);

        return parent::__toArray();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreateDate(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreateDate', []);

        return parent::getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreateDateObject(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreateDateObject', []);

        return parent::getCreateDateObject();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreateDate(\DateTimeInterface $date): \App\Entity\BaseEntity
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreateDate', [$date]);

        return parent::setCreateDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastUpdate(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastUpdate', []);

        return parent::getLastUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastUpdate(): \App\Entity\BaseEntity
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastUpdate', []);

        return parent::setLastUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function getActive(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActive', []);

        return parent::getActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setActive(bool $active): \App\Entity\BaseEntity
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActive', [$active]);

        return parent::setActive($active);
    }

}
