<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ManualOrderReport extends \App\Entity\ManualOrderReport implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\ManualOrderReport' . "\0" . 'id', '' . "\0" . 'App\\Entity\\ManualOrderReport' . "\0" . 'customerName', '' . "\0" . 'App\\Entity\\ManualOrderReport' . "\0" . 'customerCity', '' . "\0" . 'App\\Entity\\ManualOrderReport' . "\0" . 'freight', '' . "\0" . 'App\\Entity\\ManualOrderReport' . "\0" . 'discount', '' . "\0" . 'App\\Entity\\ManualOrderReport' . "\0" . 'transporter', '' . "\0" . 'App\\Entity\\ManualOrderReport' . "\0" . 'port', '' . "\0" . 'App\\Entity\\ManualOrderReport' . "\0" . 'comments', '' . "\0" . 'App\\Entity\\ManualOrderReport' . "\0" . 'orderStatus', '' . "\0" . 'App\\Entity\\ManualOrderReport' . "\0" . 'paymentType', '' . "\0" . 'App\\Entity\\ManualOrderReport' . "\0" . 'manualProductCarts', '' . "\0" . 'App\\Entity\\ManualOrderReport' . "\0" . 'travelTruckOrders', 'lastUpdate'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\ManualOrderReport' . "\0" . 'id', '' . "\0" . 'App\\Entity\\ManualOrderReport' . "\0" . 'customerName', '' . "\0" . 'App\\Entity\\ManualOrderReport' . "\0" . 'customerCity', '' . "\0" . 'App\\Entity\\ManualOrderReport' . "\0" . 'freight', '' . "\0" . 'App\\Entity\\ManualOrderReport' . "\0" . 'discount', '' . "\0" . 'App\\Entity\\ManualOrderReport' . "\0" . 'transporter', '' . "\0" . 'App\\Entity\\ManualOrderReport' . "\0" . 'port', '' . "\0" . 'App\\Entity\\ManualOrderReport' . "\0" . 'comments', '' . "\0" . 'App\\Entity\\ManualOrderReport' . "\0" . 'orderStatus', '' . "\0" . 'App\\Entity\\ManualOrderReport' . "\0" . 'paymentType', '' . "\0" . 'App\\Entity\\ManualOrderReport' . "\0" . 'manualProductCarts', '' . "\0" . 'App\\Entity\\ManualOrderReport' . "\0" . 'travelTruckOrders', 'lastUpdate'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ManualOrderReport $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setActive(bool $active): \App\Entity\ManualOrderReport
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActive', [$active]);

        return parent::setActive($active);
    }

    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerName', []);

        return parent::getCustomerName();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerName(string $customerName): \App\Entity\ManualOrderReport
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerName', [$customerName]);

        return parent::setCustomerName($customerName);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomerCity(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomerCity', []);

        return parent::getCustomerCity();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomerCity(string $customerCity): \App\Entity\ManualOrderReport
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomerCity', [$customerCity]);

        return parent::setCustomerCity($customerCity);
    }

    /**
     * {@inheritDoc}
     */
    public function getPaymentType(): ?\App\Entity\PaymentType
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPaymentType', []);

        return parent::getPaymentType();
    }

    /**
     * {@inheritDoc}
     */
    public function setPaymentType(?\App\Entity\PaymentType $paymentType): \App\Entity\ManualOrderReport
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPaymentType', [$paymentType]);

        return parent::setPaymentType($paymentType);
    }

    /**
     * {@inheritDoc}
     */
    public function getFreight(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFreight', []);

        return parent::getFreight();
    }

    /**
     * {@inheritDoc}
     */
    public function setFreight(float $freight): \App\Entity\ManualOrderReport
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFreight', [$freight]);

        return parent::setFreight($freight);
    }

    /**
     * {@inheritDoc}
     */
    public function getDiscount(): ?float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDiscount', []);

        return parent::getDiscount();
    }

    /**
     * {@inheritDoc}
     */
    public function setDiscount(?float $discount): \App\Entity\ManualOrderReport
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDiscount', [$discount]);

        return parent::setDiscount($discount);
    }

    /**
     * {@inheritDoc}
     */
    public function getTransporter(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTransporter', []);

        return parent::getTransporter();
    }

    /**
     * {@inheritDoc}
     */
    public function setTransporter(?string $transporter): \App\Entity\ManualOrderReport
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTransporter', [$transporter]);

        return parent::setTransporter($transporter);
    }

    /**
     * {@inheritDoc}
     */
    public function getPort(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPort', []);

        return parent::getPort();
    }

    /**
     * {@inheritDoc}
     */
    public function setPort(?string $port): \App\Entity\ManualOrderReport
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPort', [$port]);

        return parent::setPort($port);
    }

    /**
     * {@inheritDoc}
     */
    public function getComments(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getComments', []);

        return parent::getComments();
    }

    /**
     * {@inheritDoc}
     */
    public function setComments(?string $comments): \App\Entity\ManualOrderReport
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setComments', [$comments]);

        return parent::setComments($comments);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderStatus(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderStatus', []);

        return parent::getOrderStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setOrderStatus(int $status): \App\Entity\ManualOrderReport
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOrderStatus', [$status]);

        return parent::setOrderStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getManualProductCarts(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getManualProductCarts', []);

        return parent::getManualProductCarts();
    }

    /**
     * {@inheritDoc}
     */
    public function addManualProductCart(\App\Entity\ManualProductCart $manualProductCart): \App\Entity\ManualOrderReport
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addManualProductCart', [$manualProductCart]);

        return parent::addManualProductCart($manualProductCart);
    }

    /**
     * {@inheritDoc}
     */
    public function removeManualProductCart(\App\Entity\ManualProductCart $manualProductCart): \App\Entity\ManualOrderReport
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeManualProductCart', [$manualProductCart]);

        return parent::removeManualProductCart($manualProductCart);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderFinalPrice(): float
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderFinalPrice', []);

        return parent::getOrderFinalPrice();
    }

    /**
     * {@inheritDoc}
     */
    public function getTravelTruckOrders(): ?\App\Entity\TravelTruckOrders
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTravelTruckOrders', []);

        return parent::getTravelTruckOrders();
    }

    /**
     * {@inheritDoc}
     */
    public function setTravelTruckOrders(?\App\Entity\TravelTruckOrders $travelTruckOrders): \App\Entity\ManualOrderReport
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTravelTruckOrders', [$travelTruckOrders]);

        return parent::setTravelTruckOrders($travelTruckOrders);
    }

    /**
     * {@inheritDoc}
     */
    public function getProductsAmount(): int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProductsAmount', []);

        return parent::getProductsAmount();
    }

    /**
     * {@inheritDoc}
     */
    public function __toArray(): ?array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toArray', []);

        return parent::__toArray();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreateDate(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreateDate', []);

        return parent::getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreateDateObject(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreateDateObject', []);

        return parent::getCreateDateObject();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreateDate(\DateTimeInterface $date): \App\Entity\BaseEntity
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreateDate', [$date]);

        return parent::setCreateDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastUpdate(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastUpdate', []);

        return parent::getLastUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastUpdate(): \App\Entity\BaseEntity
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastUpdate', []);

        return parent::setLastUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function getActive(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActive', []);

        return parent::getActive();
    }

}
