<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TravelTruckOrders extends \App\Entity\TravelTruckOrders implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\TravelTruckOrders' . "\0" . 'id', '' . "\0" . 'App\\Entity\\TravelTruckOrders' . "\0" . 'driverName', '' . "\0" . 'App\\Entity\\TravelTruckOrders' . "\0" . 'departureDate', '' . "\0" . 'App\\Entity\\TravelTruckOrders' . "\0" . 'kmout', '' . "\0" . 'App\\Entity\\TravelTruckOrders' . "\0" . 'orderId', '' . "\0" . 'App\\Entity\\TravelTruckOrders' . "\0" . 'checkedOrders', 'lastUpdate'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\TravelTruckOrders' . "\0" . 'id', '' . "\0" . 'App\\Entity\\TravelTruckOrders' . "\0" . 'driverName', '' . "\0" . 'App\\Entity\\TravelTruckOrders' . "\0" . 'departureDate', '' . "\0" . 'App\\Entity\\TravelTruckOrders' . "\0" . 'kmout', '' . "\0" . 'App\\Entity\\TravelTruckOrders' . "\0" . 'orderId', '' . "\0" . 'App\\Entity\\TravelTruckOrders' . "\0" . 'checkedOrders', 'lastUpdate'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TravelTruckOrders $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getDriverName(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDriverName', []);

        return parent::getDriverName();
    }

    /**
     * {@inheritDoc}
     */
    public function setDriverName(?string $driverName): \App\Entity\TravelTruckOrders
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDriverName', [$driverName]);

        return parent::setDriverName($driverName);
    }

    /**
     * {@inheritDoc}
     */
    public function getDepartureDate(): ?\DateTime
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDepartureDate', []);

        return parent::getDepartureDate();
    }

    /**
     * {@inheritDoc}
     */
    public function setDepartureDate(?\DateTime $departureDate): \App\Entity\TravelTruckOrders
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDepartureDate', [$departureDate]);

        return parent::setDepartureDate($departureDate);
    }

    /**
     * {@inheritDoc}
     */
    public function getKmout(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getKmout', []);

        return parent::getKmout();
    }

    /**
     * {@inheritDoc}
     */
    public function setKmout(?string $kmout): \App\Entity\TravelTruckOrders
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setKmout', [$kmout]);

        return parent::setKmout($kmout);
    }

    /**
     * {@inheritDoc}
     */
    public function getOrderId(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOrderId', []);

        return parent::getOrderId();
    }

    /**
     * {@inheritDoc}
     */
    public function addOrderId(\App\Entity\ManualOrderReport $orderId): \App\Entity\TravelTruckOrders
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addOrderId', [$orderId]);

        return parent::addOrderId($orderId);
    }

    /**
     * {@inheritDoc}
     */
    public function removeOrderId(\App\Entity\ManualOrderReport $orderId): \App\Entity\TravelTruckOrders
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeOrderId', [$orderId]);

        return parent::removeOrderId($orderId);
    }

    /**
     * {@inheritDoc}
     */
    public function getCheckedOrders(): ?array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCheckedOrders', []);

        return parent::getCheckedOrders();
    }

    /**
     * {@inheritDoc}
     */
    public function setCheckedOrders(array $checkedOrders): \App\Entity\TravelTruckOrders
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCheckedOrders', [$checkedOrders]);

        return parent::setCheckedOrders($checkedOrders);
    }

    /**
     * {@inheritDoc}
     */
    public function __toArray(): ?array
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toArray', []);

        return parent::__toArray();
    }

    /**
     * {@inheritDoc}
     */
    public function __toString(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreateDate(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreateDate', []);

        return parent::getCreateDate();
    }

    /**
     * {@inheritDoc}
     */
    public function getCreateDateObject(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCreateDateObject', []);

        return parent::getCreateDateObject();
    }

    /**
     * {@inheritDoc}
     */
    public function setCreateDate(\DateTimeInterface $date): \App\Entity\BaseEntity
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCreateDate', [$date]);

        return parent::setCreateDate($date);
    }

    /**
     * {@inheritDoc}
     */
    public function getLastUpdate(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLastUpdate', []);

        return parent::getLastUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function setLastUpdate(): \App\Entity\BaseEntity
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLastUpdate', []);

        return parent::setLastUpdate();
    }

    /**
     * {@inheritDoc}
     */
    public function getActive(): bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getActive', []);

        return parent::getActive();
    }

    /**
     * {@inheritDoc}
     */
    public function setActive(bool $active): \App\Entity\BaseEntity
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setActive', [$active]);

        return parent::setActive($active);
    }

}
