<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJD9H5cQ\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJD9H5cQ/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerJD9H5cQ.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerJD9H5cQ\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerJD9H5cQ\App_KernelProdContainer([
    'container.build_hash' => 'JD9H5cQ',
    'container.build_id' => 'fed090d2',
    'container.build_time' => 1675696837,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJD9H5cQ');
